iBridges-for-iRODS/iBridges

Tutorial_irodsConnector.ipynb, ibridges/irodsconnector/meta.py, ibridges/irodsconnector/session.py, pyproject.toml
I added an __init__ function so that a metadata object is always linked to a single item. This means that the convenience of supplying a list is gone and needs to be done at another level.
I also changed the behavior of the update/set function. I think it is more intuitive if the set function always removes the data regardless if it there were already key/value pairs.
Feedback is appreciated!
=> "Improve" metadata class by making it simpler

Tutorial_irodsConnector.ipynb, ibridges/irodsconnector/permission.py, ibridges/irodsconnector/permissions.py
Streamlined permissions, added bits to the tutorial notebook.
Not sure if we require a minimum version of `python-irodsclient` is, but if we do and it's at last > 1.1.5, then the try/except in `available_permissions()` can go.
`__repr__` currently copies the output of the `repr()` of the underlying `iRODSAccess` objects (like `<iRODSAccess read_object /nluu12p/home/research-test-christine/books/Dracula.txt m.d.schermer@uu.nl(rodsuser) nluu12p>`), let me know if that works. For collections, the value for the inheritance-state is added to the list.
=> Permissions

docker/.gitattributes
@chStaiger I think I just got the gitattributes file from your repo. Is there any reason to have git consider everything as a binary? I now understand why I couldn't rebase properly last time...
=> Fix gitattributes so that the files are not binary

ibridges/session.py
The documentation tells users to create a `Session` with:
```python
session = Session(irods_env_path="~/.irods/irods_environment.json", ...
```
but this will not work without some `expanduser()` directive, either by the user or by the class.  This pull request implements such a directive in the `Session` constructor with `pathlib` as a convenience for the user.
=> Expand user home directory in `irods_env_path`

README.md, docker/irods_client/tests/test_meta.py, ibridges/export_metadata.py, ibridges/meta.py
- Extended meta.py with function that exports some system metadata and user metadata as python dictionary
- Added a function that iterates over a whole collection and exports all metadata of the collection, its subcollections and all data objects as python dictionary.
Dictionary structure:
```
{
'name': name, 
'irods_id': id,
'metadata': [(avu1), (avu2), ...],
'subcollections':[
{'name': name, 
'irods_id': id,
'rel_path': relative path to the parent collection #recursive export,
'metadata': [(avu1), (avu2), ...]
}, 
...
]
'dataobjects':[{
'name': name, 
'irods_id': id,
'rel_path': relative path to the parent collection #recursive export,
'checksum': object checksum
'metadata': [(avu1), (avu2), ...]
},
...
]
}
```
=> 72 export metadata

ibridges/data_operations.py, ibridges/sync.py, tutorials/Data_sync.ipynb
**Catching all errors in `_download_collection` and `_upload_collection`**
- The local upload path or the irods download path on which the operation fails will be printed
- The representation of the error will be printed
- The iteration over the collection will continue
=> Improving the error when upload or download fails

pyproject.toml
When testing with iBridges I ran into some already solved python_irodsclient bugs.
This let me to discover that the version was fixed to 1.1.6 in the iBridges toml file.
A brief chat with Christine confirmed the tests where ran agains python_irodsclient v2.0 
I updated the toml, build the package locally. It now build against python_irodsclient v2.0.0
=> updated toml to allow newer python irods client versions

ibridges/__main__.py
It would be nice if it didn't try to output the version of metasyn..
=> Fix ibridges output for `ibridges --version`

ibridges/rules.py, tutorials/QuickStart.ipynb
A request for two small changes in the rule engine. 
The reason for these is that at WUR we would like to run python based rules on the server. 
1. Support for different types of rules the 'irods_rule_engine_plugin-irods_rule_language-instance' is really cool. However, I hope many user, like me, will also like the 'irods_rule_engine_plugin-python-instance'. The new implementation defaults to the 'irods_rule_language', but it gives user the option to work with the other plugins.
2. Currently the rule file must be on the users machine. It would also be nice to have the ability to run rules which are available on the server. With this small change users can do both. The naming is taken from the python irods client, not saying it's the clearest.
Curious to hear what you think.
=> generalizing rules

ibridges/data_operations.py
The keyword `kw.ALL_kw` triggers that all replicas in the system will be overwritten if the user overwrites existing data. This might conflict with data versioning policies of  specific iRODS servers. Hence we should leave it to the server to decide which replicas should be updated and not force it through the client.
=> Remove kw_ALL from obj_put

ibridges/__main__.py
Also removal of unused code
Now the following are supported:
`download "irods:test.txt"`  # previous behavior
`download "irods://~/test.txt"`
`download "irods://zone/home/user/test.txt`
=> Support url-like behavior

ibridges/__main__.py, ibridges/path.py
The `assert` statement in `path.py` caused me some headaches when working on unit tests for https://github.com/UtrechtUniversity/ibridges-ansible. I was getting `AssertionError` and assumed this was being triggered by my mock objects, but it turns out I was just passing in the wrong object for session, I was thereby triggering an `AssertError` from within iBridges itself.
I think `AssertionError` should [probably not be thrown to control ordinary program flow](https://www.askpython.com/python/built-in-methods/assertions-in-python). I've replaced the `assert`s with `ValueError`s here, but maybe another error class makes even more sense.
=> Don't use assert for control flow

docker/irods_client/tests/test_sync.py, ibridges/__main__.py, ibridges/data_operations.py, ibridges/path.py, ibridges/sync.py
A new version of the synchronization method that fixes #157, because it does only checksum the files that might be overwritten. Some rudimentary performance checks indicate it is also faster for the download version, could just be random though.
This also fixes an issue related to the `IrodsPath.walk` method that made subcollections appear twice and made the procedure very slow.
=> Sync update

ibridges/__main__.py
This PR adds a new feature to the CLI that makes it possible to print the collection/subcollection tree.
Currently there is an issue with the tree being slow + subcollections showing up twice. This should be fixed after #158 is merged. I suggest we merge that PR first before merging this one.
=> Add tree for the iBridges CLI

ibridges/data_operations.py
If the checksum is the same. It is currently confusing that there is a difference between uploading collections and dataobjects in this regard.
=> Don't perform operations for files/dataobjects

ibridges/data_operations.py
Fixes #191 
Also disables progress bar if number of up/downloads == 0.
=> Fix operations with no up or download

ibridges/search.py
Previously we were only search through the session.home when the path pattern did not start with `/`. Now we should be able to find all data.
Test:
```
res = search_data(session, path="%/New Folder") # --> two folders in our yoda instance
```
```
res = search_data(session, path="%") # --> will time out, search through whole iRODS instance
```
=> Treat path as string pattern

ibridges/data_operations.py, ibridges/session.py
The current dynamic setting of the connection_timeout in the pool does not work as expected. We're returning for now to using a static connection timeout. Since users will be more likely run into a timeout that is too short, we'll increase the default timeout to a large number for now. This can still be set to a lower amount in the irods_environment.json file if needed.
Fixes #197
=> Change default connection timeout to 25000

docs/source/faq.rst
This might be helpful to users who get a NetworkError, because they are checksumming for more than 7 hours.
=> Add question for NetworkError

ibridges/interactive.py
In R the command  `system("ibridges init")` did not pick up the password from the R commandline. 
This is a small fix for this.
=>  Small change to be able to call the interactive auth from within R

ibridges/__main__.py, ibridges/util.py, tutorials/02-iRODS-paths.ipynb
Two small things:
- create .irods folder for user, if it does not exist
- Add a line in the IrodsPath tutorials showing how to create a collection
=> 225 irods folder

docker/irods_client/tests/test_sync.py, ibridges/__main__.py, ibridges/data_operations.py, ibridges/interactive.py, ibridges/util.py
This PR changes more than expected. There is currently no way to delete aliases either, but that is probably okay for now (just delete your `.ibridges/ibridges_cli.json` file).
Example:
ibridges init ~/.irods/ienv_its.json --alias its
ibridges init ~/.irods/ienv_youth.json --alias youth
ibridges init its  # Old .irodsA gets copied, no password needed
ibridges init youth
ibridges init # Use ~/.irods/irods_environment.json
=> Implement aliases for the CLI

docker/irods_client/tests/test_ticket.py, ibridges/tickets.py
Rename the listing function for tickets
Switch to IrodsPath
=> Switch to IrodsPath, rename function

docker/irods_catalog_provider/entrypoint.sh, docker/irods_client/tests/conftest.py, docker/irods_client/tests/test_util.py, ibridges/data_operations.py, ibridges/util.py
=> Check for md5 checksums if remote uses that

docker/irods_client/tests/test_data_ops.py, ibridges/data_operations.py
Most of the work is simply to add better tests for overwrite and ignore_err flags. The behavior is now when a file/data object already exists is as follows:
overwrite==False, ignore_err=False -> FileExistError
overwrite==True, ignore_err=False -> checksum -> copy
overwrite==False, ignore_err=True -> Skip with warning
overwrite==True, ignore_err=True -> checksum -> copy
Fixes #253
=> Fix overwrite / ignore_err flags in upload and download

.github/workflows/integration-tests-yoda.yml, docker/README.md, docs/source/cli.rst, docs/source/faq.rst, docs/source/index.rst, docs/source/ipath.rst, ibridges/__main__.py, pyproject.toml
Merge when everything is moved.
=> Change all the links to the new organization

ibridges/session.py
I believe this fixes the actual cause of the reason that iBridges-for-iRODS/iBridges-GUI#273 was created. (That was not so much the missing authentication scheme, but the fact that a non-pam password needs to be obfuscated)
=> store actual password when no pam negotiation has happened

docker/irods_client/tests/test_meta.py, docs/source/metadata.rst, ibridges/meta.py
This PR improves the internals of the MetaData class. Instead of relying on the PRC `iRODSMeta` class, a new class is created (`MetaDataItem`) which encapsulates one entry of the metadata for a data object or collection.
New features:
- Use `meta["some_key"]` to quickly get an entry for some key.
- Use `meta.find_all(key=..., value=..., units=...)` to find metadata entries.
- Rename keys/values/units with `meta["some_key"].key = "new_key"`
Fixes #277 (Open a new issue in the GUI repository if necessary)
=> MetaData rework

docs/source/irods_search.rst, ibridges/icat_columns.py, ibridges/path.py, ibridges/search.py
To give some performance boost when searching for data objects the search function will now return a `CachedIrodsPath` and set the the checksum and the size to the value the search returns.
That gives a splendid improvement. 
```
import time
search_start = time.time()
data = search_data(session, path_pattern="%.txt")
search_end = time.time()
print(f"Search time {search_end-search_start}")
for d in data:
d.size
size_end = time.time()
print(f"Size time {size_end-search_end}")
```
- Returning and IrodsPath for data objects and fetching the size
```
Search time 2.733164072036743
Size time 67.01198482513428
```
- Returning a CachedIrodsPath with values from search
```
Search time 2.3439738750457764
Size time 0.0004801750183105469
```
=> Search: Returning CachedIrodsPath for data objects

docker/irods_client/tests/test_cli.py, docs/source/cli.rst, ibridges/__main__.py, ibridges/meta.py, ibridges/path.py
Adds:
- `ibridges meta-show`: show the metadata for a collection or dataobject.
- `ibridges meta-add`: Add one new metadata entry for a collection or dataobject.
- `ibridges meta-del`: Delete one, multiple or all metadata items using the key/value/units.
- `ibridges list --metadata`: List the collection, including all metadata of the listed items.
- `ibridges list --short`: Mimics Unix `ls` with no options.
- `ibridges list --long`: Shows checksums and sizes of data objects.
- `ibridges ls` alias for `ibridges list`
- `ibridges meta` alias for `ibridges meta-list`
Deprecates:
- `MetaData.set`: I think we should remove this method for 2.0, since the behavior can be easily emulated with two commands (delete/add).
Improvements:
- `IrodsPath.walk`: Performance with depth==1 should be improved …
=> Add basic metadata options to CLI

.github/workflows/integration-tests-yoda.yml
Ensure that we use the same branch for the Docker setup, ruleset and portal.
=> CI: Fix Yoda integration tests

ibridges/session.py
See #299 for the issue. The problem is that the PRC behaves different when supplying the irods environment by file or by arguments. It seems that without the file, the login using the cached password in the `.irodsA` file doesn't work. This is rather a hack by creating a temporary file from the dictionary, any suggestions for improvement are appreciated.
Fixes #299
=> Workaround PRC different behavior file/dictionary

docker/irods_client/tests/test_cli.py, docs/source/cli.rst, docs/source/ipath.rst, docs/source/session.rst, ibridges/__main__.py, ibridges/cli/__init__.py, ibridges/cli/config.py, ibridges/interactive.py, ibridges/path.py, ibridges/session.py, pyproject.toml, tests/test_irodspath.py, tutorials/02-iRODS-paths.ipynb
Also add cd/pwd subcommands. Should only really affect the CLI.
TODO:
Examples:
```shell
> ibridges alias geo ~/.irods/irods_env_geo.json
> ibridges alias
geo -> /home/qubix/.irods/irods_env_geo.json
* its -> /home/qubix/.irods/irods_env_its.json
dgk -> /home/qubix/.irods/irods_env_dgk.json
> ibridges alias --delete its
> ibridges cd "test_collection"
> ibridges pwd
> ibridges cd # Back to home collection
> ibridges cd .. # One collection up
> ibridges ls # Print collections and data objects in current location.
```
Every command that now uses the implied irods_home collection, now uses the current working directory. So, now "irods:~/some_collection" is not necessarily the same as "irods:some_collection".
A change is that the `~/.ibridges/ibridges_cli.json` is now basically mandatory. …
=> Rework aliases to make them more user friendly
