iBridges-for-iRODS/iBridges

Tutorial_irodsConnector.ipynb, irodsConnector/__init__.py, irodsConnector/keywords.py, irodsConnector/resources.py, irodsConnector/session.py
- Improvement on session
- Stripping of init files
- Adding tutorial jupyter notebook
Tackling #3
=> Resources fix

ibridges/irodsconnector/session.py
Error messages for default_resource and when irods parameters lack the irods_client_server_policy
=> Fixes  error messages in session

.github/workflows/main.yml, Tutorial_iRODS_paths.ipynb, Tutorial_irodsConnector.ipynb, ibridges/__init__.py, ibridges/irodsconnector/data_operations.py, ibridges/irodsconnector/permissions.py, ibridges/irodsconnector/session.py, ibridges/utils/path.py, tests/test_dummy.py, tests/test_irodspath.py
And reimplement some of its methods.
=> Remove inheritance on pathlib

Tutorial_irodsConnector.ipynb, ibridges/data_query.py, ibridges/search.py
Refactored and optimised the data search function.
=> Search function

Tutorial_irodsConnector.ipynb, docker/irods_client/environments/plain-irods/config.toml, docker/irods_client/environments/yoda/config.toml, docker/irods_client/tests/test_ticket.py, ibridges/irodsconnector/tickets.py
I have modified the Tickets class a little bit to make it slightly easier to work with (in my opinion). Feedback is of course welcome.
One thing that I ran into is that although a datetime is used as input for the tickets, it returns a timestamp at midnight. Is that expected behavior?
=> Update Tickets class to use datetime as input

ibridges/irodsconnector/permissions.py, ibridges/irodsconnector/session.py, ibridges/search.py
Removed the hard coded path, it was not necessary anyways.
Also fixes the output of the search #52
=> Bugfix: hardcoded environment path

README.md
=> Fix capitalization of tutorials

ibridges/data_operations.py, ibridges/search.py, ibridges/tickets.py
Avoiding TypeError in older Python versions.
=> Feature py37 types

ibridges/session.py, tutorials/01-Setup-and-connect.ipynb, tutorials/QuickStart.ipynb
=> Add close method to session and remove __del__

docker/irods_client/tests/test_sync.py, ibridges/sync.py, tutorials/Data_sync.ipynb
Reduced the number of checksum parameters.
Fixes #84
=> 84 simplify checksum in sync

docker/irods_client/tests/test_session.py, docs/source/api.rst, docs/source/quickstart.rst, ibridges/data_operations.py, ibridges/export_metadata.py, ibridges/icat_columns.py, ibridges/interactive.py, ibridges/meta.py, ibridges/path.py, ibridges/resources.py, ibridges/search.py, ibridges/session.py, ibridges/tickets.py
=> Improve errors

ibridges/sync.py, tutorials/Data_sync.ipynb
=> fixed checksum-check NoneType  error

tutorials/QuickStart.ipynb
- Removed os module, since pathlib does the same
- Separated the single steps in *Upload a file or folder*
- Ticket creation on demofile.txt
- adjust path for test rule
=> Removing os module, tickets switched to demofile

ibridges/interactive.py, ibridges/session.py
- Fix bug: NetworkException has no attribute msg
- Add function `get_user_info` for GUI
=> Fix session

ibridges/data_operations.py
Extends the local path in `_obj_get` if the path is a directory.
=> Temporary fix for #126

ibridges/data_operations.py
- Creates the whole subtree when a folder is uploaded or a collection is downloaded; including empty collections and folders respectively.
=> Empty folders and collections

docker/irods_client/tests/test_move.py, ibridges/path.py
New function in IrodsPath to move/rename data objects and collections.
=> Move data objects and collections

ibridges/session.py
Small bugfix when irods_environment does not contain minimal information.
=> Check for host and port before checking network

.github/dependabot.yml, docker/irods_client/tests/test_move.py, docs/requirements.txt, ibridges/__main__.py, ibridges/path.py, ibridges/session.py
- Cli: add mkcoll
- API: make network check available as function
- Pipeline: dependabot
=> Next minor version

docs/source/index.rst, docs/source/install.rst
Add install documentation to RTD
=> Install doc

.github/workflows/main.yml, ibridges/__main__.py, ibridges/data_operations.py, ibridges/interactive.py, ibridges/path.py, ibridges/rules.py, ibridges/session.py, pyproject.toml
The checks will fail, because I saw that the PRs from @chStaiger  would fix them anyway.
=> Fix docstring formatting error

README.md
Saw some small errors in the readme.
=> Fix spelling errors in the README

docs/source/api/full_reference.rst, ibridges/__main__.py, ibridges/data_operations.py, ibridges/meta.py, ibridges/path.py, ibridges/session.py
Add examples to the doc strings for the sphinx API documentation.
=> Add examples

README.md, tutorials/02-iRODS-paths.ipynb
- Extend timeout to long data transfers
- Update readme
=> New minor release

docs/source/faq.rst
This should help users who might run into issues with their PATH (which is common for inexperienced command line users).
=> Add question if ibridges not in PATH

ibridges/__main__.py
=> Fix issue where root collection lists itself

ibridges/data_operations.py
=> Ignore symlinks creating operations

docker/irods_client/tests/test_move.py, docs/source/conf.py, ibridges/__init__.py, ibridges/__main__.py, ibridges/data_operations.py, ibridges/export_metadata.py, ibridges/icat_columns.py, ibridges/interactive.py, ibridges/meta.py, ibridges/path.py, ibridges/permissions.py, ibridges/resources.py, ibridges/rules.py, ibridges/search.py, ibridges/session.py, ibridges/tickets.py, ibridges/util.py, pyproject.toml, tests/test_irodspath.py
Adjust configuration pyproject and documentation
Bugfix: remove double search results
=> Prep v1.0.0

docker/irods_client/tests/test_meta.py, docs/source/api/full_reference.rst, docs/source/data_transfers.rst, ibridges/data_operations.py, ibridges/executor.py, ibridges/icat_columns.py, ibridges/interactive.py, ibridges/meta.py, ibridges/path.py, ibridges/permissions.py, ibridges/resources.py, ibridges/rules.py, ibridges/search.py, ibridges/session.py, ibridges/tickets.py, ibridges/util.py
Some modules were also not yet in the API documentation.
Fixes #228
=> Update docstrings across the board

ibridges/meta.py
=> Fix f-string issue in error message

ibridges/executor.py
Replaces #209 
This implementation works for both PRC 2.1 (with improved progress bars) and PRC<2.1 (without improved progress bars).
=> Modify progress bar to be updated during single files

ibridges/executor.py
=> Fix obj_put not setting overwrite flag

docker/irods_client/tests/test_search.py, docs/source/cli.rst, ibridges/search.py, tutorials/00-FirstSteps.ipynb, tutorials/04-Metadata.ipynb
=> 250 tutorials search

docs/source/faq.rst, ibridges/session.py, pyproject.toml
- Checking if connection_timeout is a number
- Setting limit to maximum if exceeded and inform through a warning.
- Adjust FAQ
=> 263 timeout

docs/source/faq.rst
- Adding data transfer flags to FAQs
- Adding info for `org_` metadata to FAQs
=> extending faqs

.gitignore, docs/source/data_transfers.rst, docs/source/ipath.rst, docs/source/irods_search.rst, docs/source/metadata.rst, docs/source/quickstart.rst, docs/source/session.rst
Before moving to the new location, I went through the RTD documents again and made some small edits. No major changes.
=> Small edits, code formatting and typos

docker/irods_client/tests/test_search.py, ibridges/search.py
Solves: https://github.com/chStaiger/iBridges-Gui/issues/269
=> add param case_sensitive, by default False.

ibridges/data_operations.py, ibridges/executor.py
=> Allow the tqdm progress bar to be disabled

tutorials/04-Metadata.ipynb
Adjusting the metadata tutorial to the new `MetaData` and `MetaDataItem` classes.
=> 285 metadata tutorial

docker/irods_client/tests/test_data_ops.py, docker/irods_client/tests/test_path.py, ibridges/data_operations.py, ibridges/exception.py, ibridges/path.py
@maartenschermer Would this be more suitable for you? I haven't looked everywhere to fix all the ValueError that are somewhat non-descriptive. We could also add new exceptions (DataObjectNotFoundError, etc.), but this might be in the end easier for the developer/user in the end?
=> Move from Value -> fnf/nad error

ibridges/__main__.py
=> Fix: setup no longer unintentionally overwrites existing env-file
